spring:
  application:
    name: item-image-fetch

server:
  port: 8080

webclient:
  timeout:
    connect: 5000  # ms
    read: 5000     # ms
    write: 5000    # ms
  max-connections: 100

image-fetch:
  strategy:
    direct-url:
      timeout: 50       # ms
    sales-url:
      timeout: 200      # ms
    channel-search:
      timeout: 300      # ms
  max-results: 3
  allowed-formats:
    - jpg
    - jpeg
    - png
    - gif
    - webp

logging:
  level:
    com.example.imagefetch: DEBUG
    org.springframework.web: INFO