spring:
  application:
    name: item-image-fetch

server:
  port: 8080

webclient:
  timeout:
    connect: 5000  # ms
    read: 5000     # ms
    write: 5000    # ms
  max-connections: 100

image-fetch:
  strategy:
    direct-url:
      timeout: 50       # ms
    sales-url:
      timeout: 200      # ms
    channel-search:
      timeout: 3000     # ms (increased for anti-crawling measures)
  max-results: 3
  allowed-formats:
    - jpg
    - jpeg
    - png
    - gif
    - webp
  google-search:
    api-key: ${GOOGLE_API_KEY}  # Set via environment variable
    cx: ${GOOGLE_SEARCH_CX}     # Custom Search Engine ID
    enabled: true               # Enable Google Image Search fallback

logging:
  level:
    com.example.imagefetch: DEBUG
    org.springframework.web: INFO